---
- hosts: rails-ansible
  vars:
  - ubuntu_releas: trusty

  tasks:
    name: Update APT package cache
    action: apt update_cache=yes

    name: Upgrade APT to the latest version
    action: apt update=safe

    name: Add HTTPS to support APT
    action: pkg=apt-transport-https

    name: Add user deploy
    action: user name=deploy password=$deploy_password

    name: Add authorized deploy key
    action: authorized_key user=deploy key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Remove sudo group rights
    lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent

  - name: Add deploy user to sudoers
    lineinfile: "dest=/etc/sudoers regexp='deploy ALL' line='deploy ALL=(ALL) NOPASSWD: ALL' state=present"

  - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: Restart ssh

  - name: Install unattended-upgrades
    apt: pkg=unattended-upgrades state=present

  - name: Setup ufw
    action: shell ufw allow 22/tcp

  - name: Setup ufw
    action: shell ufw allow 443/tcp

  - name: Setup ufw
    action: shell ufw allow 60023/udp

  - name: Enable ufw
    action: shell echo 'y' | ufw enable

  - name: Change root password
    action: user name=root password=$root_password

  - name: Disallow root SSH access
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
    notify: Restart ssh

  handlers:
  - name: Restart ssh
    action: service name=ssh state=restarted